"""migrate_all

Revision ID: b7927d1acde3
Revises: 
Create Date: 2024-07-15 20:39:37.343876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7927d1acde3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_code', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=512), nullable=False),
    sa.Column('inserted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_code'),
    sa.UniqueConstraint('campaign_name')
    )
    op.create_table('api_company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=512), nullable=False),
    sa.Column('inserted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('api_content',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('api_code', sa.BigInteger(), nullable=False),
    sa.Column('id_campaign', sa.Integer(), nullable=True),
    sa.Column('id_company', sa.Integer(), nullable=True),
    sa.Column('user_type', sa.String(length=45), nullable=False),
    sa.Column('to', sa.String(length=255), nullable=True),
    sa.Column('mailer', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('inserted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_campaign'], ['api_campaign.id'], ),
    sa.ForeignKeyConstraint(['id_company'], ['api_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_content')
    op.drop_table('api_company')
    op.drop_table('api_campaign')
    # ### end Alembic commands ###
